### ISSUE TITLE
"Switch To" Button Error: Route [login] Not Defined

### ISSUE THREAD

**Issue by radimnemecek** [DutchCodingCompany/filament-developer-logins#15]
The "Switch To" button on the top bar does not function as expected. When clicked, it triggers an error message: "Route [login] not defined."

**Comment by caweb** [comment]
same here, did you find a solution?

**Comment by bramr94** [comment]
I am aware of this issue, I'm very busy at the moment in my personal life. I will try to fix this as soon as possible.

**Comment by grafst** [comment]
tried to find the bug but I am to dumb
