### ISSUE TITLE
Frequently land on `/filament-developer-logins` with 419

### ISSUE THREAD

**Issue by bilogic** [DutchCodingCompany/filament-developer-logins#24]
Hi 

Thanks for this very helpful plugin!

I often find myself landing on `/filament-developer-logins` an expired csrf token 419, would be great if it could be redirected back to the login page instead or something.

Or perhaps remove the csrf check for only login?

**Comment by bramr94** [comment]
I can't say I've ever encountered this issue. When does this occur?

**Comment by bilogic** [comment]
Hmm, I have to check again, but I frequenly run `artisan migrate:fresh`, not sure if that could be a reason.

**Comment by bramr94** [comment]
I will close this issue for now, if the issue persists feel free to open this issue again.
